platform :ios, '9.0'

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Mapbox-iOS-SDK', '~> 5.1.0'
end

target 'annotations-framework-extension' do
  shared_pods
end

target 'annotationapp' do
  shared_pods
end